[package]
name = "client-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aws_lambda_events = { workspace = true }
lambda-otel-lite = { workspace = true }
lambda_runtime = { workspace = true }
opentelemetry = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
