[package]
name = "otlp-forwarder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
aws_lambda_events = { workspace = true, features = ["kinesis"] }
lambda-otel-lite = { workspace = true }
lambda_runtime = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
otlp-stdout-span-exporter = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serverless-otlp-forwarder-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
