import { join } from "node:path";
import { TerraformStack } from "cdktn";
import type { Construct } from "constructs";
import { IamRole } from "../../.gen/providers/aws/iam-role/index.js";
import { IamRolePolicyAttachment } from "../../.gen/providers/aws/iam-role-policy-attachment/index.js";
import { LambdaFunction } from "../../.gen/providers/aws/lambda-function/index.js";
import { AwsProvider } from "../../.gen/providers/aws/provider/index.js";
import { DataNodeLambdaPackagerPackage } from "../../.gen/providers/node-lambda-packager/data-node-lambda-packager-package/index.js";
import { NodeLambdaPackagerProvider } from "../../.gen/providers/node-lambda-packager/provider/index.js";

const functionDir = join(import.meta.dirname, "../functions/sample");

export class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new AwsProvider(this, "AwsProvider");
    new NodeLambdaPackagerProvider(this, "NodeLambdaPackagerProvider");

    // IAM Role for Lambda
    const lambdaRole = new IamRole(this, "LambdaRole", {
      name: "lambda-role",
      assumeRolePolicy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "lambda.amazonaws.com",
            },
            Action: "sts:AssumeRole",
          },
        ],
      }),
    });

    // IAM Role Policy for Lambda
    new IamRolePolicyAttachment(this, "LambdaRolePolicyAttachment", {
      role: lambdaRole.name,
      policyArn: "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    });

    // SampleLambda zipped package generated by esbuild
    const sampleLambdaPackage = new DataNodeLambdaPackagerPackage(this, "SampleLambdaPackage", {
      args: [
        "--bundle",
        "--minify",
        "--sourcemap",
        "--platform=node",
        "--target=es2024",
        // Pin the Lambda's tsconfig; esbuild otherwise walks up to the app's
        `--tsconfig=${join(functionDir, "tsconfig.json")}`,
      ],
      entrypoint: join(functionDir, "index.ts"),
      workingDirectory: functionDir,
    });

    // SampleLambda function
    new LambdaFunction(this, "SampleLambda", {
      functionName: "sample-lambda",
      role: lambdaRole.arn,
      runtime: "nodejs24.x",
      filename: sampleLambdaPackage.filename,
      sourceCodeHash: sampleLambdaPackage.sourceCodeHash,
      handler: "index.handler",
      architectures: ["arm64"],
      memorySize: 1024,
      timeout: 1,
      loggingConfig: { logFormat: "JSON" },
    });
  }
}
